### ISSUE TITLE
Terminal color is not visible

### ISSUE THREAD

**Issue by ovidiubute** [ovidiubute/scry-css#15]
The color for `Sorry, no suggestions are available` is not visible on all terminals, it must be switched to white.

![screen shot 2016-10-06 at 10 22 50 am](https://cloud.githubusercontent.com/assets/462561/19143812/e8f8f7a4-8bae-11e6-854c-7fe58a3bc08f.png)

**Comment by divayprakash** [comment]
@ovidiubute I'd like to take this up!

**Comment by ovidiubute** [comment]
@divayprakash it looks like you've been beaten to it 😄  maybe take a look at #14 ?
